### PR TITLE
added support for docker-compose

### PR DESCRIPTION
**Pull request by rbonthond**
perhaps this is useful for others, it allows one to quick spin up this starter pack via docker-compose.

### CODE REVIEW

**Comment by johnymontana** [comment]
Thanks @rbonthond ! This is great. The only problem I see is that by using `neo4j` and `api` in api/.env for the host will break when not using docker since those hosts won't be defined. 

Maybe we could keep the current `localhost` values, but add in the quickstart section of the readme that these should be changed to `neo4j` and `api` when using docker?

**Comment by rbonthond** [comment]
@johnymontana not sure how to resolve that, I had to add those settings to get docker-compose to work, else they wouldn't authenticate. I can see if there's other ways to resolve this, else I'll update the README. Note that I'm also settings the neo4j default password in the docker file, that should probably also part of the documentation.

**Comment by rbonthond** [comment]
@johnymontana I've updated the pull request with defaults back to what they were, and updated the documentation on what needs to be changed.

**Comment by johnymontana** [comment]
Thanks, that's probably the best option. Thanks for the update (and the PR) @rbonthond!

**Pull request merged**
